export const FETCH_NODE_VIEW = 'FETCH_NODE_VIEW';
export const FETCH_SERVICE_VIEW = 'FETCH_SERVICE_VIEW';
export const FETCH_MPS_VIEW = 'FETCH_MPS_VIEW';

export const UPDATE_VIEW = 'UPDATE_VIEW';

export const FETCH_NODE_INFO = 'FETCH_NODE_INFO';
export const FETCH_SERVICE_INFO = 'FETCH_SERVICE_INFO';

export const UPDATE_SEARCH_DATA = 'UPDATE_SEARCH_DATA';
