export const FETCH_NODE_VIEW = 'FETCH_NODE_VIEW';
export const FETCH_SERVICE_VIEW = 'FETCH_SERVICE_VIEW';
export const FETCH_MPS_VIEW = 'FETCH_MPS_VIEW';

export const UPDATE_TREE = 'UPDATE_TREE';

export const FETCH_NODE_DETAILS = 'FETCH_NODE_DETAILS';
export const FETCH_SERVICE_DETAILS = 'FETCH_SERVICE_DETAILS';
export const RESET_DETAILS = 'RESET_DETAILS';

export const UPDATE_KEYWORD = 'UPDATE_KEYWORD';
export const UPDATE_FOUND_COUNT = 'UPDATE_FOUND_COUNT';
export const UPDATE_FOCUS_INDEX = 'UPDATE_FOCUS_INDEX';
