export const UPDATE_TREE = 'UPDATE_TREE';

export const FETCH_NODE_DETAILS = 'FETCH_NODE_DETAILS';
export const FETCH_SERVICE_DETAILS = 'FETCH_SERVICE_DETAILS';
export const RESET_DETAILS = 'RESET_DETAILS';


